// Generated by scripts/build-plugin-manifest.mjs — do not edit.
export const MANIFEST = {
  "languageVersion": "1.2.0",
  "files": [
    {
      "path": "guide/checker.js",
      "sha256": "cd39d573250f9398b1e1d6c4a1198e293fd0699d7742f3a92f81adf8bb700de7"
    },
    {
      "path": "guide/fixer.js",
      "sha256": "d0163f85f309b70b3db488017d57571ee39bcfe6331484bd563e65ad6a8d3bcd"
    },
    {
      "path": "viewers/eml-model.js",
      "sha256": "090f528833df743568c2bea2bec04b2c3ab20ad8a6603dfdbfd88c73db7449e1"
    },
    {
      "path": "plugin/appwithai-eml.js",
      "sha256": "52430926be57d02e7e6dbe4b96aa40f1c3680b4b805028e54d0b16b04f8f91b0"
    },
    {
      "path": "plugin/app.js",
      "sha256": "2edda6131837f1bdc16dd83e1b6eee91d075b41ba99389a62559c692f445bba6"
    }
  ]
};
