// Generated by scripts/build-plugin-manifest.mjs — do not edit.
export const MANIFEST = {
  "languageVersion": "1.2.0",
  "files": [
    {
      "path": "guide/checker.js",
      "sha256": "1658fe7636b1f139b06d5bc048f3315c2a47f2e5df9f7da86810ee5723dc97cf"
    },
    {
      "path": "guide/fixer.js",
      "sha256": "0a20d56040949eeaddf8e64a5e7a5ccec7c522f8f66f188ac8562451ecf97db3"
    },
    {
      "path": "viewers/eml-model.js",
      "sha256": "4faf3b50fa357478e49fecc2919d0d8f5007db434d36699f7d13d2ad85efcb8f"
    },
    {
      "path": "plugin/appwithai-eml.js",
      "sha256": "fbb587af08b8384b1a415a5fac83e43c16938d01a2d7fb819636dc4c7163cb8e"
    },
    {
      "path": "plugin/app.js",
      "sha256": "3f05c207dd5172abbecfae45acd0bbf938787076921e3596f724c01f28a3fadc"
    }
  ]
};
